import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import './navbar.css';
import { ClerkLoaded, ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });
import Link from "next/link";
import Navbar from "./components/Navbar/Navbar"
import ImageAvatars from './components/Avatar/Avatar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            {/* <nav className="navbar">

              <ul className="logo-section">
                <li><ImageAvatars /></li>
                <li>Orka</li>
              </ul>

              <ul className="items-section">
                <ClerkLoaded>
                  <li>
                    <ul className="navbar-links">
                      <li><Link href={"/"}>Home</Link></li>
                      <li><Link href={"/editor"}>Problems</Link></li>
                      <li>Compiler</li>
                    </ul>
                  </li>
                </ClerkLoaded>

                <li>
                  <SignedOut><SignInButton /></SignedOut>
                  <SignedIn><UserButton /></SignedIn>
                </li>
              </ul>
            </nav> */}
            <Navbar/>
          </header>

          <main className = "main_div" style={{height:"100%"}}>
            <ClerkLoaded>
            {children}
            </ClerkLoaded>
          </main>
          
        </body>
      </html>
    </ClerkProvider>
  );
}



