import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import './navbar.css';
import { ClerkLoaded, ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });
import {Providers} from "./Providers"
import Navbar from "./components/Navbar/Navbar"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <Providers>
          <header>  
            <Navbar/>
            
          </header>

          <main className = "main_div" style={{height:"100%"}}>
            <ClerkLoaded>
            {children}
            </ClerkLoaded>
          </main>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}



