import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./navbar.module.css"
import { ClerkLoaded, ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
        {/* style={{height:"70vh"}} */}
          <header>
            <nav className={styles.nav}>
              <ul className={styles.ul}>
            <ClerkLoaded>
            <li>
            <ul className={styles.inside_ul}>
            <li>
              <Link href={"/"}>
              Home
              </Link>
            </li>
            <li>
              <Link href={"/editor"}>
              Problems
              </Link>
              </li>
            </ul>
            </li>
            </ClerkLoaded>

            <li>
              
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
            </li>
            </ul>
            </nav>
          </header>

          <main className = "main_div" style={{height:"100%"}}>
            <ClerkLoaded>
            {children}
            </ClerkLoaded>
          </main>
          
        </body>
      </html>
    </ClerkProvider>
  );
}
